language:
- objective-c
env:
  global:
  - LATEST_TAG=1 # comment out to build version in submodule
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.6.1 # tune to taste
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate numpy==$NUMPY_VERSION
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag numexpr; fi
  - cd numexpr
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..
script:
  # install dependencies for tests e.g - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  # Run the tests
  - cd ..
before_deploy: cd numexpr/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "Ml3/Pvl52m6NX2aA4L/ZScnM4M2AHkS98rKxNahUtqmwC2F0Dk6aAdKVI9ECC60ipUWaWi1G/v0SWc11tlSh+X0oqKGJsVVkVVTrPN33Q00pOvKlZFFgYLNADdcjaAIXlkgcvRGFYVnxZh5JUNoohIGn7rvLWDwlQxZuIUL7DZc="
  region: ORD
  container: wheels
  skip_cleanup: true
