language:
- objective-c
env:
  global:
  - LATEST_TAG=1 # comment out to build version in submodule
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.6.1 # tune to taste
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate numpy==$NUMPY_VERSION
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag numexpr; fi
  - cd numexpr
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  # install dependencies for tests e.g - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  - python -c 'import sys, numexpr; sys.exit(not numexpr.test())'
  - cd ..
before_deploy: cd numexpr/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "FhFaaBn2Gu0FYTsrEX0ObwrAwRonst1BdbStGOjcdrRI2jQNPho9qVqViHcGGPzUQ1bN7pADIf0ZuNHIWVnkHiJ7gqwvZIlU96X3nHc7GIoQsR5YzG4MEpnkRya1loi6Yg/1tF7Jaqe8NT2iCY08WmTI0AIQ1TS8883doLT5msg="
  region: ORD
  container: wheels
  skip_cleanup: true
